# help.R — short interpretation notes shown in each tab header (panel help) and
# in an info-popover on each card (how to read it / what to watch / why it matters).

VIEW_HELP <- list(
  recession = "The 'are we okay?' panel: four US recession signals. The two yield curves are leading: before each recession since 1982 the 10Y–3M curve's monthly average turned negative 8–16 months before the NBER peak. The Sahm rule and the recession probability are coincident: from 1969 to 2020 the Sahm rule crossed 0.5 between two months before and four months after each peak.",
  conditions = "Financial conditions and liquidity, the first link in the dashboard's transmission chain. The NFCI and the St. Louis Fed stress index are 0 at their historical averages; positive values mean tighter or more stressed than average. Net liquidity is the Fed's total assets minus the Treasury's account and overnight reverse repos.",
  credit_rates = "Credit and interest rates. The loan officer survey shows whether banks are tightening lending standards; the ICE BofA spreads show the extra yield corporate bonds pay over Treasuries; the rest are policy rates and government bond yields for the US and other major economies.",
  inflation = "US and international inflation. Breakevens and the Michigan survey measure expected inflation; CPI, PCE, PPI and HICP measure prices, as changes over 12 months. Targets: the Fed's 2% is for PCE inflation, the ECB's 2% for euro-area HICP inflation over the medium term, the Bank of England's 2% for UK CPI inflation, and the Bank of Japan has a 2% price stability target.",
  cycle = "Growth momentum and turning points. The first five tiles place the US, the euro area, the UK, Japan and China in one of four growth-and-inflation regimes, after Bridgewater's four economic environments. The OECD leading indicators are read by direction; the OECD finds turning points in GDP about 4 to 8 months, on average, after its indicators signal them. The dashboard classes the surveys and orders as leading, industrial production as coincident and GDP as lagging.",
  labor = "US labour-market indicators from the weekly claims to the monthly jobs report, plus unemployment rates for the UK, Japan and Germany. The dashboard classes claims, quits, openings, temp-help employment and hours as leading, payrolls as coincident and the US unemployment rate as lagging.",
  trade_energy = "Supply-chain pressure and commodity prices. The New York Fed's Global Supply Chain Pressure Index combines shipping and airfreight costs with PMI supply indicators for seven economies; oil, natural gas and copper are market benchmark prices. The dashboard classes all five tiles as leading.",
  consumer = "US consumers and housing: the Michigan sentiment index, building permits, housing starts, new home sales, the 30-year mortgage rate and real retail sales. The dashboard classes all but retail sales as leading; real retail sales are coincident.",
  markets = "Market prices and news-based uncertainty: the S&P 500 (licensed, so link-only on the public site), the VIX, the Federal Reserve's broad dollar index, and Baker, Bloom and Davis's economic policy uncertainty indexes for the US and the world.",
  china = "China, India, Korea and Brazil: the OECD leading indicators for the four, and consumer-price inflation for China and India from the IMF's CPI dataset. The PMIs for China and India are licensed and appear as links.",
  bubbles = "The speedometer: valuation and leverage gauges for how little margin of safety is left, not for when a fall will come. In the design brief's words the speedometer is not a clock, and it should be read against the windscreen (Recession Watch, Conditions) rather than alone."
)

CARD_HELP <- list(
  # --- recession watch ---
  curve_10y_3m = "10-year minus 3-month Treasury yield; below 0 = inverted. Before each recession since the series began in 1982, its monthly average turned negative 8–16 months before the NBER peak. The inversions of 2022–25 had not been followed by a recession as of October 2026.",
  curve_10y_2y = "10-year minus 2-year Treasury yield; below 0 = inverted. Its monthly average turned negative 10–22 months before each NBER peak from 1980 to 2007, but not before the February 2020 peak. It tends to turn negative earlier and more often than the 10Y–3M curve (Estrella and Trubin, 2006).",
  sahm_realtime = "Real-time Sahm rule: the 3-month average unemployment rate minus its low of the previous 12 months, in percentage points; 0.5 is the trigger. From 1969 to 2020 it crossed 0.5 between two months before and four months after each NBER peak. It also reached 0.5 in November 1976 and July–September 2024 without a recession.",
  recession_prob_chauvet_piger = "Smoothed probability (%) that the US was in recession in a given month, from Chauvet and Piger's model of payrolls, industrial production, real income excluding transfers and real manufacturing and trade sales. It reads the present, not the future. Piger: three consecutive months above 80% has historically signalled a new recession. The 20% and 50% badge bands are the dashboard's own.",
  # --- financial conditions ---
  nfci = "Chicago Fed National Financial Conditions Index: a weighted average of 105 financial measures, 0 = average since 1971. Positive = tighter than average, negative = looser. It was above 0 in 29% of weeks since 1971, most recently in May 2020.",
  anfci = "Adjusted NFCI: financial conditions after removing the part attributable to economic activity and inflation. Positive = tighter than the economy would typically produce; negative = looser.",
  stl_financial_stress = "St. Louis Fed Financial Stress Index (version 4), built from 18 weekly interest rates, yield spreads and other indicators. 0 = normal market stress; above 0 = more stressed than average. Its highest weekly readings came in October 2008 and March 2020.",
  # --- liquidity ---
  fed_balance_sheet = "Total assets of the Federal Reserve (Wednesday level, $ millions). It peaked at $8.97 trillion in April 2022, shrank under quantitative tightening until the FOMC ended the run-off on 1 December 2025, and has grown since with Treasury bill purchases.",
  treasury_general_account = "The US Treasury's general account at the Fed (week average, $ millions). On the Fed's balance sheet it absorbs reserve funds: other things equal, a higher balance means lower bank reserves.",
  reverse_repo = "Overnight reverse repos with the Fed ($ billions): money funds, banks, GSEs and dealers placing cash with the Fed overnight against Treasuries, which shifts the Fed's liabilities from bank reserves to reverse repos. Usage peaked at $2.55 trillion in December 2022 and has been below $100 billion almost every day since August 2025.",
  net_liquidity = "Fed total assets minus the Treasury General Account minus overnight reverse repos ($ millions), computed by this dashboard. Both subtracted items absorb reserve funds, so a rise means more of the Fed's balance sheet is left as bank reserves, currency and other liabilities.",
  m2 = "M2 money stock, change over 12 months (%). Below 0 = smaller than a year earlier, which in the series since 1959 happened only from December 2022 to February 2024; growth peaked at 26.8% in February 2021.",
  # --- credit ---
  sloos_ci_tightening = "Fed Senior Loan Officer Survey: the net percentage of banks tightening standards for C&I loans to large and middle-market firms (tightened minus eased). Above 0 = more banks tightening than easing. It peaked at 83.6% in the October 2008 survey.",
  hy_oas = "ICE BofA US High Yield option-adjusted spread: the extra yield of below-investment-grade (BB or lower) US corporate bonds over Treasuries, in %. The badge bands are the dashboard's own. Licensed: link-only on the public site; since April 2026 FRED keeps only the last three years.",
  ig_oas = "ICE BofA US Corporate option-adjusted spread: the extra yield of investment-grade (BBB or better) US corporate bonds over Treasuries, in %. Licensed: link-only on the public site; since April 2026 FRED keeps only the last three years.",
  hy_minus_ig = "High-yield spread minus investment-grade spread, in percentage points: how much more the market charges below-investment-grade borrowers. The badge bands are the dashboard's own. Licensed inputs: link-only on the public site; since April 2026 FRED keeps only the last three years of them.",
  ust10y_realized_vol = "Realized volatility of the 10-year Treasury yield: the standard deviation of the last 21 daily changes, annualized, in basis points. It looks back over the past month; the dashboard uses it in place of the licensed ICE BofA MOVE index. Its median since 1962 is 78 bp.",
  # --- rates ---
  ust_3m = "3-month Treasury constant-maturity yield (H.15). Since December 2008 it has tracked the effective federal funds rate closely (correlation 0.997). The short leg of the 10Y–3M curve.",
  ust_2y = "2-year Treasury constant-maturity yield (H.15). The short leg of the 10Y–2Y curve.",
  ust_10y = "10-year Treasury constant-maturity yield (H.15): the long leg of both recession curves and the bond side of the US stocks-vs-bonds tile. Its lowest close was 0.52% (4 August 2020).",
  effr = "Effective federal funds rate: the volume-weighted median of overnight federal funds trades, from the New York Fed. It has stayed inside the FOMC's target range on all but four days since December 2008, so it shows where policy is set.",
  ecb_policy_rate = "ECB deposit facility rate: what banks earn on overnight deposits with the Eurosystem; since March 2024 the ECB steers its policy stance through it. A step series that changes only on decision dates.",
  # --- inflation ---
  breakeven_5y = "5-year breakeven inflation rate: the 5-year Treasury yield minus the 5-year TIPS yield, which FRED describes as the average inflation market participants expect over the next 5 years. The 2.3% reference line and the badge bands are the dashboard's own.",
  breakeven_10y = "10-year breakeven inflation rate: the 10-year Treasury yield minus the 10-year TIPS yield, the average inflation market participants expect over the next 10 years (FRED). The 2.3% reference line and the badge bands are the dashboard's own.",
  breakeven_5y5y_fwd = "5-year, 5-year forward inflation expectation rate: the average inflation expected over the five years that begin five years from now, derived by FRED from the 5- and 10-year breakevens. The 2.3% reference line and the badge bands are the dashboard's own.",
  umich_inflation_exp_1y = "University of Michigan Surveys of Consumers: the median price change consumers expect over the next 12 months. FRED shows it with a one-month delay by agreement with the source. Since 2020 it peaked at 6.6% (May 2025).",
  cpi_headline = "US CPI for all urban consumers, all items: change over 12 months (%), from the BLS index (seasonally adjusted). FRED has no October 2025 value, so that month and October 2026 have none here. The Fed's 2% goal refers to PCE inflation, not CPI.",
  cpi_core = "US CPI excluding food and energy (core CPI): change over 12 months (%), from the BLS index (seasonally adjusted). FRED has no October 2025 value, so that month and October 2026 have none here.",
  pce_core = "US PCE price index excluding food and energy (BEA): change over 12 months (%). The FOMC's 2% longer-run goal is for the annual change in the overall PCE price index; this core measure excludes food and energy.",
  ppi_final_demand = "US producer price index for final demand (BLS, index from November 2009): change over 12 months (%). There is no target for it, so no reference line or badge.",
  # --- cycle ---
  growth_inflation_regime = "Which of four growth-and-inflation regimes the US is in. Bridgewater describes four economic environments, growth and inflation each rising or falling relative to expectations; this tile reads the direction instead. Growth: the 3-month change in the OECD leading indicator for the US. Inflation: CPI inflation minus its average over the past 12 months, so a price jump counts as rising until it leaves the average. Above zero counts as rising; the regime names are the dashboard's. Since 1960 the regime has changed about 2.4 times a year. Pick a period with the handles under the strip, by dragging across the strip, or (on the public site) with the zoom; the quadrant traces that period, its last 12 months dark. The chart is the same in every display mode. The OECD revises recent months of its indicator; FRED has no October 2025 CPI, which this tile fills in log-linearly.",
  regime_euro_area = "The four growth-and-inflation regimes for the euro area, built like the US tile. Growth: the 3-month change in the OECD leading indicators for Germany, France, Italy and Spain, combined with GDP weights (the OECD's dataset has no euro-area indicator). Inflation: euro-area HICP inflation (Eurostat, the euro area in its changing composition) minus its average over the past 12 months. The history starts in December 1997. Pick a period with the handles under the strip, by dragging across the strip, or (on the public site) with the zoom; the quadrant traces that period, its last 12 months dark. The chart is the same in every display mode.",
  regime_uk = "The four growth-and-inflation regimes for the UK, built like the US tile. Growth: the 3-month change in the OECD leading indicator for the UK. Inflation: CPI inflation (ONS) minus its average over the past 12 months. The history starts in December 1989, as the ONS CPI annual rate begins in January 1989. Pick a period with the handles under the strip, by dragging across the strip, or (on the public site) with the zoom; the quadrant traces that period, its last 12 months dark. The chart is the same in every display mode.",
  regime_japan = "The four growth-and-inflation regimes for Japan, built like the US tile. Growth: the 3-month change in the OECD leading indicator for Japan. Inflation: CPI inflation, from the IMF's CPI dataset, minus its average over the past 12 months. The history starts in 1960. Pick a period with the handles under the strip, by dragging across the strip, or (on the public site) with the zoom; the quadrant traces that period, its last 12 months dark. The chart is the same in every display mode.",
  regime_china = "The four growth-and-inflation regimes for China, built like the US tile, read by direction rather than level, so inflation rising from below 1% still counts as rising. Growth: the 3-month change in the OECD leading indicator for China. Inflation: CPI inflation, from the IMF's CPI dataset, minus its average over the past 12 months. The history starts in December 1994. Pick a period with the handles under the strip, by dragging across the strip, or (on the public site) with the zoom; the quadrant traces that period, its last 12 months dark. The chart is the same in every display mode.",
  oecd_cli = "OECD composite leading indicator for the G20 (amplitude adjusted, the OECD's headline CLI). The OECD designs its CLIs to signal turning points and reads the direction of change rather than its size; it finds turning points in GDP about 4 to 8 months, on average, after the CLI signals them. The dashboard reads 100 as trend.",
  core_capex_orders = "Census Bureau: manufacturers' new orders for nondefense capital goods excluding aircraft, change over 12 months (%). Since 1993 the range has been −32% (April 2009) to +25% (April 2021).",
  cli_usa = "OECD composite leading indicator for the US (amplitude adjusted), the growth input of the US regime tile. Since 1955 it has averaged 100.0 and been at or above 100 in 54% of months. The dashboard reads 100 as trend.",
  empire_state_mfg = "New York Fed Empire State Manufacturing Survey: the general business conditions diffusion index for New York State (seasonally adjusted), the survey's headline index. Above 0, more firms reported better conditions than worse. The survey goes to about 200 manufacturing executives each month; about 100 reply.",
  philly_fed_mfg = "Philadelphia Fed Manufacturing Business Outlook Survey: the current general activity diffusion index, the percentage of firms reporting increases minus the percentage reporting decreases (seasonally adjusted). Above 0, more firms reported increases.",
  industrial_production = "Federal Reserve industrial production (manufacturing, mining, and electric and gas utilities): change over 12 months (%). Since 1960 it has been negative in 24% of months.",
  real_gdp = "US real GDP growth, BEA's headline measure: % change from the preceding quarter at a seasonally adjusted annual rate. It has been negative in 44 quarters since 1947, most recently in the first quarter of 2022.",
  # --- labor ---
  initial_claims = "Initial claims for unemployment insurance (US Employment and Training Administration), weekly, seasonally adjusted: claims filed by people after a separation from an employer. The badge turns amber when the latest week is more than 15% above the lowest of the past 52 weeks, the dashboard's own rule; since 1970 that was so in 31% of weeks.",
  continuing_claims = "Continued claims (insured unemployment): people who have already filed an initial claim and claim benefits for a week of unemployment; weekly, seasonally adjusted. Same badge rule as initial claims; since 1970 it read 'Rising off lows' in 24% of weeks.",
  jolts_quits_rate = "Quits as a percentage of total nonfarm employment (BLS Job Openings and Labor Turnover Survey), monthly. Since December 2000 it has ranged from 1.2% (August 2009) to 3.0% (November 2021).",
  jolts_openings = "Job openings (BLS JOLTS), thousands: positions open on the last business day of the month, with work available that can start within 30 days and active recruiting. They peaked at 12.3 million in March 2022; in August 2026 there were about 1.0 openings per unemployed person.",
  temp_help_employment = "Employees in temporary help services (BLS establishment survey), thousands. Before the 2001, 2007 and 2020 recessions it peaked 11 to 19 months before the NBER peak.",
  avg_weekly_hours_mfg = "Average weekly hours of production and nonsupervisory employees in manufacturing (BLS): the hours they were paid for, which can be lower than scheduled hours.",
  nonfarm_payrolls = "Change in total nonfarm payroll employment from the previous month (BLS), in thousands. Payroll employment covers about 80% of the workers who contribute to GDP (FRED). It fell in seven months from January 2025 to September 2026.",
  unemployment_rate = "US unemployment rate (U-3, BLS household survey): the unemployed as a percentage of the labour force, aged 16 and over. It feeds the Sahm rule on the Recession Watch tab.",
  # --- trade / energy / commodities ---
  gscpi = "New York Fed Global Supply Chain Pressure Index: the common component of shipping and airfreight costs and of PMI delivery times, backlogs and purchased stocks for seven economies, each cleaned of demand effects, in standard deviations from its average since 1997. The badge bands are the dashboard's own. Its highest reading was 4.43, in December 2021.",
  brent = "Brent crude oil spot price (EIA via FRED, US$ per barrel). The EIA describes Brent as a blended North Sea crude that serves as a reference price for other crude streams. Its highest daily price was $143.95 on 3 July 2008.",
  wti = "West Texas Intermediate crude oil spot price at Cushing, Oklahoma (EIA via FRED, US$ per barrel), a reference price for other crude streams. It closed at −$36.98 on 20 April 2020, the only negative day in the series.",
  henry_hub_gas = "Henry Hub natural gas spot price (EIA via FRED, US$ per million BTU), for delivery at the Henry Hub in Louisiana. Its highest daily price since 1997 was $30.72, on 23 January 2026.",
  copper_global = "Global price of copper (IMF via FRED, US$ per metric ton, monthly average), a benchmark the IMF describes as representative of the global market. The badge reads the change over three months: above +1% rising, below −1% falling, the dashboard's own rule.",
  # --- consumer / housing ---
  umich_sentiment = "University of Michigan Index of Consumer Sentiment (Surveys of Consumers; 1966:Q1 = 100). FRED shows it a month late at the source's request. Its lowest value on FRED is 44.8, in May 2026.",
  retail_sales_control_group = "Real retail and food services sales: Census advance retail sales deflated by CPI (computed by the St. Louis Fed, FRED RRSFS), change over 12 months (%). FRED's CPI has no October 2025 value, so this tile has none for October 2025 or October 2026.",
  building_permits = "New privately owned housing units authorized by building permits (Census Bureau and HUD), seasonally adjusted annual rate, thousands. Its highest month in the three years before each NBER peak since 1969 came 3 to 31 months before the peak.",
  housing_starts = "New privately owned housing units started (Census Bureau and HUD), seasonally adjusted annual rate, thousands. A start is when excavation begins for the footings or foundation. Census attaches a range of ±12.0% to the August 2026 monthly change, wider than the change itself.",
  new_home_sales = "New single-family houses sold (Census Bureau and HUD), seasonally adjusted annual rate, thousands. Census attaches a range of ±19.5% to the August 2026 monthly change.",
  mortgage_rate_30y = "Freddie Mac's 30-year fixed-rate mortgage average, weekly. Since 17 November 2022 it is based on applications lenders submit to Freddie Mac. Since 1971 it has ranged from 2.65% (January 2021) to 18.63% (October 1981).",
  # --- markets / uncertainty ---
  sp500 = "S&P 500 price index at the daily close (S&P Dow Jones Indices via FRED), without dividends; FRED's notes say it covers 75% of US equities. Licensed: link-only on the public site, and FRED keeps only 10 years of daily history.",
  vix = "Cboe Volatility Index (VIX): the market's expectation of near-term volatility conveyed by stock index option prices (FRED). The badge bands are the dashboard's own; since 1990 the index was below 20 on 63% of days and at 30 or above on 8%.",
  broad_usd = "Federal Reserve nominal broad US dollar index (January 2006 = 100): the dollar against the currencies of 26 economies, weighted by their share of US goods and services trade. A rise means a stronger dollar.",
  epu_us_daily = "Economic policy uncertainty, US, daily (Baker, Bloom and Davis): built from US newspaper articles that contain terms on the economy, on uncertainty and on policy (Congress, deficit, Federal Reserve, legislation, regulation, White House), normalised by the number of articles. Daily values are noisy, and the last 30 days are revised each day.",
  epu_global = "Global economic policy uncertainty (Baker, Bloom and Davis): a GDP-weighted average of newspaper-based national indexes for 18 countries, each re-normalised to a mean of 100 over 1997–2015 (current-price GDP weights). Its highest value was 621, in April 2025.",
  # --- bubbles ---
  buffett_indicator = "US nonfinancial corporate equity (Federal Reserve Financial Accounts) divided by GDP, computed by this dashboard. Since 1947 its median is 0.69; it first exceeded 1.5 in the fourth quarter of 1999 and 2 in the first quarter of 2021, and its highest value, 2.55, is the latest (second quarter of 2026). The badge bands are the dashboard's own.",
  stocks_vs_bonds_euro_area = "Built like the US tile from ECB data: the after-tax earnings yield of euro-area non-financial corporations (net entrepreneurial income minus current taxes over four quarters, over the equity they have issued) against the ECB's AAA 10-year yield minus the longer-term inflation expectation in its Survey of Professional Forecasters. The badge ranks the gap against its own history since September 2004; on 28 September 2026 it was the narrowest in that history.",
  stocks_vs_bonds_uk = "Built like the euro-area tile from ONS data for UK private non-financial corporations, against the Bank of England's 10-year real zero-coupon gilt yield. The badge ranks the gap against its own history since December 1997. The ONS profitability data that give depreciation end in the second quarter of 2025, so the tile continues depreciation at its growth over the year before.",
  stocks_vs_bonds_real = "Two yields the dashboard, after Ray Dalio, reads as expected real returns: the earnings yield of US nonfinancial corporations (after-tax profits over their corporate equities) and the 10-year Treasury yield minus the Cleveland Fed's 10-year expected inflation. The value is the gap. It was last negative on 28 June 2002; its narrowest since then was 0.63, on 5 October 2026. The badge bands (0 and 1) are the dashboard's own. Profits are quarterly, so the stocks line moves in quarterly steps and between them only bonds move the gap.",
  real_10y_yield = "Yield on 10-year US Treasury inflation-indexed securities at constant maturity (Federal Reserve H.15, via FRED), %. Since 2003 it has been negative on 16% of days, most recently on 28 April 2022.",
  ipo_spac_issuance = "IPO and SPAC issuance in the US. The dashboard has no free, republishable feed for it, so the tile links to public trackers (Renaissance Capital, SPACInsider).",
  case_shiller_price_rent = "S&P Cotality Case-Shiller US national home price index divided by the CPI for rent of primary residence, computed by this dashboard. Licensed: link-only on the public site. The two indexes have different base periods, so read the ratio's changes and its position in its own history.",
  household_debt_service_ratio = "Household debt service ratio (Federal Reserve): required household debt payments as a percentage of disposable personal income. Since its 2024:Q2 publication the Fed uses a new, credit-bureau-based method, and the series starts in 2005. It peaked at 15.8% in the fourth quarter of 2007.",
  # --- global (G1) ---
  ea_10y = "Euro-area 10-year government bond yield: the ECB's long-term interest rate for convergence purposes (euro area in its changing composition), monthly.",
  de_10y = "German 10-year government bond yield (OECD, monthly). It was below 0 in 38 months between June 2016 and January 2022. Compare the French and Italian yields with it.",
  fr_10y = "French 10-year government bond yield (OECD, monthly). Since 1999 its spread over Germany's peaked at 1.54 percentage points, in November 2011.",
  it_10y = "Italian 10-year government bond yield (OECD, monthly). Since 1999 its spread over Germany's peaked at 5.18 percentage points, in November 2011.",
  uk_10y = "UK 10-year government bond yield (OECD, monthly). For the short end, see SONIA.",
  jp_10y = "Japanese 10-year government bond yield (OECD, monthly). It was below 0 in 24 months between February 2016 and April 2020.",
  ca_10y = "Canadian 10-year government bond yield (OECD, monthly).",
  cli_g7 = "OECD composite leading indicator for the G7 (amplitude adjusted). The dashboard reads 100 as trend.",
  cli_uk = "OECD composite leading indicator for the UK (amplitude adjusted), the growth input of the UK regime tile. The dashboard reads 100 as trend.",
  cli_japan = "OECD composite leading indicator for Japan (amplitude adjusted), the growth input of the Japan regime tile. The dashboard reads 100 as trend.",
  cli_germany = "OECD composite leading indicator for Germany (amplitude adjusted), one of the four indicators the dashboard combines into its euro-area indicator. The dashboard reads 100 as trend.",
  cli_china = "OECD composite leading indicator for China (amplitude adjusted), the growth input of the China regime tile. The dashboard reads 100 as trend; since 1992 it has been at or above 100 in 57% of months.",
  cli_india = "OECD composite leading indicator for India (amplitude adjusted). The dashboard reads 100 as trend.",
  cli_korea = "OECD composite leading indicator for Korea (amplitude adjusted). The dashboard reads 100 as trend.",
  cli_brazil = "OECD composite leading indicator for Brazil (amplitude adjusted). The dashboard reads 100 as trend.",
  unemp_uk = "UK unemployment rate, aged 16 and over, seasonally adjusted (ONS Labour Force Survey, MGSX). Each value covers three months and is dated at the middle one: the ONS's 4.9% for May to July 2026 is the June 2026 point.",
  unemp_japan = "Japan's unemployment rate, aged 15 and over, seasonally adjusted (OECD infra-annual labour statistics via FRED).",
  unemp_germany = "Germany's unemployment rate, aged 15 and over, seasonally adjusted (OECD infra-annual labour statistics via FRED).",
  hicp_ea = "Euro-area HICP inflation (Eurostat), annual rate, for the euro area in its changing composition (21 countries from 2026). The ECB aims for 2% HICP inflation over the medium term and treats deviations on either side as equally undesirable.",
  hicp_eu = "EU-27 HICP inflation (Eurostat), annual rate.",
  hicp_de = "German HICP inflation (Eurostat), annual rate.",
  hicp_fr = "French HICP inflation (Eurostat), annual rate.",
  # --- global (G2) ---
  rate_3m_euro = "3-month spot yield on AAA-rated euro-area government bonds, from the ECB's daily yield curve. Since 2004 it has averaged 0.12 percentage points above the ECB deposit rate.",
  rate_3m_uk = "SONIA, the sterling overnight rate the Bank of England administers, based on actual transactions. Since April 2018 it has stayed within 0.12 percentage points of Bank Rate, so it shows where the Bank has set policy.",
  rate_3m_japan = "Uncollateralized overnight call rate (average): the rate the Bank of Japan's policy guideline targets, raised to around 1.25% on 18 September 2026. It was negative from March 2016 to March 2024.",
  rate_3m_canada = "Canada 3-month interbank rate (OECD, monthly).",
  cpi_uk = "UK CPI inflation, annual rate (ONS, series D7G7). The Government sets the Bank of England a 2% target for CPI inflation.",
  cpi_japan = "Japan CPI inflation, % over 12 months, from the IMF's CPI dataset, which carries each economy's national all-items headline index. The Bank of Japan has a 2% price stability target.",
  cpi_china = "China CPI inflation, % over 12 months, from the IMF's CPI dataset (it matched the National Bureau of Statistics' releases for June to August 2026). No badge or reference line: no official target has been verified. Since 2023 it has been below 1% in 86% of months.",
  cpi_india = "India CPI inflation, % over 12 months, from the IMF's CPI dataset. The RBI's target is 4% CPI inflation with a tolerance band of 2–6%, retained in March 2026 for April 2026 to March 2031; the reference line is at 4 and the badge reads the band.",
  pmi_euro = "Purchasing managers' index for the euro area from S&P Global. Licensed, so the tile links to S&P Global's PMI site instead of showing data.",
  pmi_uk = "Purchasing managers' index for the UK from S&P Global. Licensed, so the tile links to S&P Global's PMI site instead of showing data.",
  pmi_japan = "Purchasing managers' index for Japan from S&P Global. Licensed, so the tile links to S&P Global's PMI site instead of showing data.",
  pmi_china = "Purchasing managers' index for China from S&P Global. Licensed, so the tile links to S&P Global's PMI releases instead of showing data.",
  pmi_india = "Purchasing managers' index for India from S&P Global. Licensed, so the tile links to S&P Global's PMI site instead of showing data."
)

#' Panel help text for a view id (empty string if none).
view_help <- function(view_id) VIEW_HELP[[view_id]] %||% ""

#' Card help text for an entry (falls back to a generic line).
card_help <- function(entry) {
  CARD_HELP[[entry$id]] %||%
    sprintf("%s — %s indicator (%s, %s).", display_title(entry),
            entry$indicator_class %||% "", entry$provider %||% "source",
            entry$frequency %||% "")
}
